sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 547055741
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wxbc794295cd0cfb1f
    secret:
    mchid: 1561414331
    mchSerialNo:
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key:
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl:
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess